2023-06-06 23:36:41,596 ERROR: Exception on /reset_password_request [POST] [in /home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/blog_1/app/routes.py", line 173, in reset_password_request
    send_password_reset_email(user)
  File "/home/anton/code_train/Flask/blog_1/app/email.py", line 21, in send_password_reset_email
    text_body=render_template('email/reset_passwod.txt',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_passwod.txt
2023-06-06 23:40:36,445 INFO: Microblog startup [in /home/anton/code_train/Flask/blog_1/app/__init__.py:58]
2023-06-06 23:40:50,243 ERROR: Exception on /reset_password_request [POST] [in /home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/blog_1/app/routes.py", line 173, in reset_password_request
    send_password_reset_email(user)
  File "/home/anton/code_train/Flask/blog_1/app/email.py", line 21, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_passwod.txt
2023-06-06 23:41:13,337 INFO: Microblog startup [in /home/anton/code_train/Flask/blog_1/app/__init__.py:58]
2023-06-06 23:41:18,350 INFO: Microblog startup [in /home/anton/code_train/Flask/blog_1/app/__init__.py:58]
2023-06-06 23:41:19,590 INFO: Microblog startup [in /home/anton/code_train/Flask/blog_1/app/__init__.py:58]
2023-06-06 23:41:46,292 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6NywiZXhwIjoxNjg2MDg0NjkxLjE3NjUzODd9.rgRgxoO9ZbqcDzBZEMzvnDzSWgWbHAFi7pLCaV9jNx0 [GET] [in /home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/blog_1/app/routes.py", line 186, in reset_password
    form = ResetPasswordForm()
           ^^^^^^^^^^^^^^^^^
NameError: name 'ResetPasswordForm' is not defined
2023-06-06 23:42:25,156 INFO: Microblog startup [in /home/anton/code_train/Flask/blog_1/app/__init__.py:58]
2023-06-06 23:42:28,427 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6NywiZXhwIjoxNjg2MDg0NjkxLjE3NjUzODd9.rgRgxoO9ZbqcDzBZEMzvnDzSWgWbHAFi7pLCaV9jNx0 [GET] [in /home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/flask/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/code_train/Flask/blog_1/app/routes.py", line 186, in reset_password
    form = ResetPasswordForm()
           ^^^^^^^^^^^^^^^^^
NameError: name 'ResetPasswordForm' is not defined
2023-06-06 23:42:42,934 INFO: Microblog startup [in /home/anton/code_train/Flask/blog_1/app/__init__.py:58]
2023-06-06 23:42:45,489 INFO: Microblog startup [in /home/anton/code_train/Flask/blog_1/app/__init__.py:58]
2023-06-06 23:42:47,809 INFO: Microblog startup [in /home/anton/code_train/Flask/blog_1/app/__init__.py:58]
